import Head from "next/head";
import { FunctionComponent, ReactNode } from "react";
import Footer from "@components/layout/Footer";
import Header from "@components/layout/Header";
import styles from "@styles/layouts/Layouts.module.scss";

interface Props {
  children?: ReactNode;
}

const Layout: FunctionComponent<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Darren's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.layout}>
        <main className={styles.main}>{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
